sudo: required
dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
addons:
  chrome: stable
script:
  - npm test
  - npm run codecov
env:
  global:
    - secure: GIyU9/k35uDA3zpSrRO+H27j/C8nXIloZfyYBwopPqFajqaVwsDzMAJ3EKati4O+6K35AFyZeg4qnfcEZZD9vBuFTdbO8HHt+kWgKKpNDjrC9fMvTIpWq2H8Orh45qlvto7fTGAMmr+d3R+Uc+A3qvTd/1zKMiVMHB8Po2xNKX5ZsAji7XrgLBw0YdGawU7mWTir1wq4bdwUIkMiWwO7/+Jti9vpndk9WrNvUzc8ZjJOpHqXxrvyEGX3xcWry6z1ORZ3EWIMvQMQz0E5XzLEP/XWv24eaHlpRflixBW5R98+UwE8sAQ/9xnxkdc0APdQ/yufzZ1S7n7EC+8PaZP3fyMLVolGevnbd0Fdrot5xOQUlOEG1HW4Yb6uUhambUOwHZlLymS9LMyo89xRtjtbewgprNA68YkYzcwKeGXOyWo7d8clD1ei2toKVT/PVKsKnNWdw7lPgbPyvlouyw8LVjzf4MYJXv8zj6aqxOx6nDpn4FfpjCUAPyK4wgW24cPe03tTRDlItmyYEo5HqRk6imQ59F21tII1Fby+JD0sWPCDHvCJUgg2K9ZTkOlyKS+LSNwJPpVrmK2fPmw4TAdQ6LCflUg2JF5wfqVFUiuJjjOi/NKXxeBaNR965AIZDkqKMD5rf+xZeGEoPbWB7MFQ6mCzMzbK93UHxuSa8eRpq/o=
    - secure: QxPZev+LFUbDByK1zQ6zHWXp+3gRbqfTvAYh0YHXPQDwFY3qR3K7KP32ezw1wfWdM2HK0YzYT/sLTuTiV94ScXuoa476h8etnwxO/XEDvLQcxyqPP+B1BzXw3Zj37o1w4OPEE7/aJ0aTdAMujuoaR5cfPooaLgfdTvp65oU9qCNy90l6Q2UUKHc58HMwPqR3Oy93dId1f9/R8aqvl7geAICcMn5bq16NQBoyCWe/xEPocfl2pFLNTSOxZZgCZgBYhYXI2A+X7pFCk+70UOshg1JzS8vpxNmTgqKsnh07rC234A1p3u9gF7cvz+y9PN9gK3DZpU7Wg+UE+BbYzw5ifTMihTh0KgCkm18iVTm/AeK4QLiGPfFjk2jiTitTENAwdy3NQwpZ4Q7IufP2f+GkjHKgDv1joxyML5v0St1pN08tb7MOt7EhZw90SJOGe3/KsP8IAArKcbS8DM4S0nWMiKUmDobUNwCX3P74ijSRx6QkZX5O3RZdToTqGoSUFVIGMAxJcCctQPl3EfdRo6fs3gZCsJcIBkiXqChDDXcNXbjO9ZVpz2lPvC6i6rkDI0N+s1XTwI87f76GLLc074kqowlLMsbPvDhEZWgDmgcsXqaUp1hSMDXMFzxUWFMXGb9YwlBttwaiON1eRJZr2D3gKx8MjN4omRl7j007ZbnfLDk=
