version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    docker:
      - image: cimg/node:20.4.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage
          command: |
            CODECOV_VERSION=v0.7.3
            curl -Os https://uploader.codecov.io/${CODECOV_VERSION}/linux/codecov
            curl -Os https://uploader.codecov.io/${CODECOV_VERSION}/linux/codecov.SHA256SUM
            sha256sum -c codecov.SHA256SUM
            chmod +x codecov && ./codecov

workflows:
  test:
    jobs:
      - test-node
