version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    docker:
      - image: cimg/node:20.4.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov

workflows:
  test:
    jobs:
      - test-node
